conf/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from ikwen_webnode.webnode.views import FlatPageView

from council.views import Home
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'conf.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    # url(r'^$', Home.as_view(), name='home'),
    url(r'^laakam/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^billing/', include('ikwen.billing.urls', namespace='billing')),
    url(r'^cashout/', include('ikwen.cashout.urls', namespace='cashout')),
    url(r'^theming/', include('ikwen.theming.urls', namespace='theming')),
    url(r'^revival/', include('ikwen.revival.urls', namespace='revival')),
    url(r'^ikwen/', include('ikwen.core.urls', namespace='ikwen')),

    url(r'^page/(?P<url>[-\w]+)/$', FlatPageView.as_view(), name='flatpage'),
    url(r'^blog/', include('ikwen_webnode.blog.urls', namespace='blog')),
    url(r'^web/', include('ikwen_webnode.web.urls', namespace='web')),
    url(r'^items/', include('ikwen_webnode.items.urls', namespace='items')),
    url(r'^echo/', include('echo.urls', namespace='echo')),
    url(r'^rewarding/', include('ikwen.rewarding.urls', namespace='rewarding')),
    url(r'^pinsview/', include('pinsview.urls', namespace='pinsview')),

    url(r'^reporting/', include('ikwen_foulassi.reporting.urls', namespace='reporting')),
    url(r'^school/', include('ikwen_foulassi.school.urls', namespace='school')),
    url(r'^foulassi/', include('ikwen_foulassi.foulassi.urls', namespace='foulassi')),
    url(r'^', include('council.urls', namespace='council')),
    url(r'^$', Home.as_view(), name='home')
)

council/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required, permission_required

from council.views import Home, PaymentOrderList, Dashboard, ChangeTax, TaxList, Receipt, ChangePaymentOrder, \
    EditProfile, ProfileList, set_momo_payment, confirm_payment, PaymentList, BookParking, Maps,\
    notify_outdated_payment_orders, ChangeProfile, ChangeBanner, BannerList, ProjectList, ChangeProject, CategoryList,\
    ChangeCategory, ChangeCheck, CheckList, SubmitBuildingLicenceApplication, SubmitWeddingApplication, \
    BuyWeddingApplication, BuyBuildingLicence, WeddingApplicationList, ChangeWeddingApplication, \
    BuildingLicenceApplicationList, ChangeBuildingLicenceApplication

urlpatterns = patterns(
    '',

    url(r'^kmth/dashboard/$', permission_required('council.ik_view_dashboard')(Dashboard.as_view()), name='dashboard'),

    url(r'^kmth/payments/$', permission_required('council.ik_manage_payment')(PaymentList.as_view()), name='payment_list'),

    url(r'^kmth/categoryList/$', permission_required('council.ik_manage_category')(CategoryList.as_view()), name='category_list'),
    url(r'^kmth/changeCategory/$', permission_required('council.ik_manage_category')(ChangeCategory.as_view()), name='change_category'),
    url(r'^kmth/changeCategory/(?P<object_id>[-\w]+)$', permission_required('council.ik_manage_category')(ChangeCategory.as_view()), name='change_category'),

    url(r'^kmth/taxList/$', permission_required('council.ik_manage_tax')(TaxList.as_view()), name='tax_list'),
    url(r'^kmth/changeTax/$', permission_required('council.ik_manage_tax')(ChangeTax.as_view()), name='change_tax'),
    url(r'^kmth/changeTax/(?P<object_id>[-\w]+)$', permission_required('council.ik_manage_tax')(ChangeTax.as_view()), name='change_tax'),

    url(r'^kmth/changeProfile/$', permission_required('council.ik_view_profile')(ChangeProfile.as_view()), name='change_profile'),
    url(r'^kmth/changeProfile/(?P<object_id>[-\w]+)/$', permission_required('council.ik_view_profile')(ChangeProfile.as_view()), name='change_profile'),
    url(r'^kmth/profileList/$', permission_required('council.ik_view_profile')(ProfileList.as_view()), name='profile_list'),

    url(r'^kmth/weddingApplicationList/$', permission_required('council.ik_manage_wedding')(WeddingApplicationList.as_view()),
        name='wedding_application_list'),
    url(r'^kmth/changeWeddingApplication/$', permission_required('council.ik_manage_wedding')(ChangeWeddingApplication.as_view()),
        name='change_weddingapplication'),
    url(r'^kmth/changeWeddingApplication/(?P<object_id>[-\w]+)$',
        permission_required('council.ik_manage_wedding')(ChangeWeddingApplication.as_view()),
        name='change_weddingapplication'),

    url(r'^kmth/buildingLicenceList/$', permission_required('council.ik_manage_building_licence')(BuildingLicenceApplicationList.as_view()),
        name='building_licence_list'),
    url(r'^kmth/changeBuildingLicence/$',
        permission_required('council.ik_manage_building_licence')(ChangeBuildingLicenceApplication.as_view()),
        name='change_buildinglicenceapplication'),
    url(r'^kmth/changeBuildingLicence/(?P<object_id>[-\w]+)$',
        permission_required('council.ik_manage_building_licence')(ChangeBuildingLicenceApplication.as_view()),
        name='change_buildinglicenceapplication'),

    url(r'^kmth/changeProject/$', permission_required('council.ik_manage_project')(ChangeProject.as_view()), name='change_project'),
    url(r'^kmth/changeProject/(?P<object_id>[-\w]+)/$', permission_required('council.ik_manage_project')(ChangeProject.as_view()), name='change_project'),
    url(r'^kmth/projectList/$', permission_required('council.ik_manage_project')(ProjectList.as_view()), name='project_list'),

    url(r'^kmth/paymentOrderList$', permission_required('council.ik_manage_payment_order')(PaymentOrderList.as_view()), name='paymentorder_list'),
    url(r'^kmth/changePaymentOrder/$', permission_required('council.ik_manage_payment_order')(ChangePaymentOrder.as_view()), name='change_paymentorder'),
    url(r'^kmth/changePaymentOrder/(?P<object_id>[-\w]+)$', permission_required('council.ik_manage_payment_order')(ChangePaymentOrder.as_view()), name='change_paymentorder'),

    url(r'^kmth/bannerList/$', permission_required('council.ik_manage_tax')(BannerList.as_view()), name='banner_list'),
    url(r'^kmth/changeBanner/$', permission_required('council.ik_manage_tax')(ChangeBanner.as_view()), name='change_banner'),
    url(r'^kmth/changeBanner/(?P<object_id>[-\w]+)$', permission_required('council.ik_manage_tax')(ChangeBanner.as_view()), name='change_banner'),

    url(r'^kmth/checkList/$', permission_required('council.ik_manage_tax')(CheckList.as_view()), name='check_list'),
    url(r'^kmth/changeCheck/$', permission_required('council.ik_manage_tax')(ChangeCheck.as_view()), name='change_check'),
    url(r'^kmth/changeCheck/(?P<object_id>[-\w]+)$', permission_required('council.ik_manage_tax')(ChangeCheck.as_view()), name='change_check'),


    # url(r'^home/$', Home.as_view(), name='home'),
    url(r'^profile/edit$', login_required(EditProfile.as_view()), name='edit_profile'),
    url(r'^maps$', login_required(Maps.as_view()), name='maps'),
    url(r'^wedding/apply$', login_required(SubmitWeddingApplication.as_view()), name='submit_wedding_application'),
    url(r'^wedding/application/buy$', login_required(BuyWeddingApplication.as_view()), name='buy_wedding_application'),
    url(r'^buildingLicence/apply$', login_required(SubmitBuildingLicenceApplication.as_view()),
        name='building_licence_application'),
    url(r'^buildingLicence/application/buy$', login_required(BuyBuildingLicence.as_view()),
        name='buy_building_licence'),
    url(r'^receipt/(?P<receipt_id>[-\w]+)/$', login_required(Receipt.as_view()), name='receipt'),
    url(r'^bookParking/$', login_required(BookParking.as_view()), name='book_parking'),

    url(r'^set_momo_payment$', set_momo_payment),
    url(r'^confirm_payment/(?P<object_id>[-\w]+)$', confirm_payment, name='confirm_payment'),
    url(r'^confirm_payment/(?P<object_id>[-\w]+)/(?P<signature>[-\w]+)$', confirm_payment, name='confirm_payment'),

    url(r'^notif$', notify_outdated_payment_orders, name='notify_outdated_payment_orders'),
)

templates/billing/snippets/payment_list_results.html
{% load i18n static humanize %}
{% include 'core/snippets/spinner.html' %}
<div class="row">
    <div class="col-xs-6 col-sm-3">
        <div class="category successful" data-status="Success">
            <h4>Mobile :
                <span class="count">{{ total_momo.count|intcomma }}</span>
            </h4>
            <div class="amount">{{ total_momo.amount|floatformat:"0"|intcomma }}</div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="col-xs-6 col-sm-3">
        <div class="category running" data-status="Running">
            <h4>{% trans "Cash" %} :
                <span class="count">{{ total_cash.count|intcomma }}</span>
            </h4>
            <div class="amount">{{ total_cash.amount|floatformat:"0"|intcomma }}</div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="col-xs-6 col-sm-3">
        <div class="category failed" data-status="Failure">
            <h4>{% trans "Bank card" %} :
                <span class="count">{{ total_bank_card.count|intcomma }}</span>
            </h4>
            <div class="amount">{{ total_bank_card.amount|floatformat:"0"|intcomma }}</div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="col-xs-6 col-sm-3">
        <div class="category dropped" data-status="Dropped">
            <h4>{% trans "Other" %} :
                <span class="count">{{ total_other.count|intcomma }}</span>
            </h4>
            <div class="amount">{{ total_other.amount|floatformat:"0"|intcomma }}</div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<ul class="object-list list-group">
    {% for payment in objects_page.object_list %}
        {% if payment.processor_tx_id %}
            {% url 'council:receipt' payment.id as obj_url %}
            <li class="ik-li list-group-item" id="{{ payment.id }}" data-id="{{ payment.id }}">
                <a href="{{ obj_url }}">{{ payment.member }}</a>
                <div>
                    <span class="pull-left text-muted hidden-xs">{{ payment.tax }} - {{ payment.created_on|date:"Y-m-d H:i" }}</span>
                    <span class="pull-left text-muted visible-xs">{{ payment.tax }}</span>
                    <span class="pull-right">
                        <span class="text-muted" style="font-size: .8em">{{ currency_symbol }}</span>
                        <strong>{{ payment.amount|intcomma }}</strong>
                    </span>
                </div>
                <div class="pull-left visible-xs text-muted" style="clear: both; font-size: .8em; margin-bottom: -10px">
                    {{ payment.created_on|date:"Y-m-d H:i" }}
                </div>
            </li>
        {% endif %}
    {% endfor %}
</ul>
{% if objects_page.paginator.num_pages > 1 %}
<ul class="pagination" style="float: left">
    {% if objects_page.paginator.num_pages > max_visible_page_count and page_range.0 >= max_visible_page_count  %}
        <li class="page" data-val="first"><a href="javascript:;" aria-label="Previous"><span aria-hidden="true">«</span></a></li>
    {% endif %}
    {% for page in page_range %}
        <li class="page{% if page == objects_page.number %} active{% endif %}" data-val="{{ page }}">
            <a href="javascript:;">
                {{ page }} {% if page == objects_page.number %}<span class="sr-only">(current)</span>{% endif %}
            </a>
        </li>
    {% endfor %}
    {% if objects_page.paginator.num_pages > max_visible_page_count and max_page < objects_page.paginator.num_pages %}
        <li class="page{% if max_page == objects_page.paginator.num_pages %} disabled{% endif %}" data-val="-1"><a href="javascript:;" aria-label="Next"><span aria-hidden="true">»</span></a></li>
    {% endif %}
</ul>
{% endif %}
<div id="page-navigation" class="text-muted">
    {% if objects_page.paginator.num_pages > 1  %}
        <p>{% blocktrans with count=objects_page.paginator.count start=objects_page.start_index end=objects_page.end_index %}
            {{ start }} – {{ end }} of {{ count }} results{% endblocktrans %}</p>
    {% else %}
        <p>{% blocktrans with count=objects_page.paginator.count %}{{ count }} results{% endblocktrans %}</p>
    {% endif %}
</div>