conf/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from ikwen_webnode.webnode.views import FlatPageView

from council.views import Home
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'conf.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    # url(r'^$', Home.as_view(), name='home'),
    url(r'^laakam/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^billing/', include('ikwen.billing.urls', namespace='billing')),
    url(r'^cashout/', include('ikwen.cashout.urls', namespace='cashout')),
    url(r'^theming/', include('ikwen.theming.urls', namespace='theming')),
    url(r'^revival/', include('ikwen.revival.urls', namespace='revival')),
    url(r'^ikwen/', include('ikwen.core.urls', namespace='ikwen')),

    url(r'^page/(?P<url>[-\w]+)/$', FlatPageView.as_view(), name='flatpage'),
    url(r'^blog/', include('ikwen_webnode.blog.urls', namespace='blog')),
    url(r'^web/', include('ikwen_webnode.web.urls', namespace='web')),
    url(r'^items/', include('ikwen_webnode.items.urls', namespace='items')),
    url(r'^echo/', include('echo.urls', namespace='echo')),
    url(r'^rewarding/', include('ikwen.rewarding.urls', namespace='rewarding')),
    url(r'^pinsview/', include('pinsview.urls', namespace='pinsview')),

    url(r'^reporting/', include('ikwen_foulassi.reporting.urls', namespace='reporting')),
    url(r'^school/', include('ikwen_foulassi.school.urls', namespace='school')),
    url(r'^foulassi/', include('ikwen_foulassi.foulassi.urls', namespace='foulassi')),
    url(r'^', include('council.urls', namespace='council')),
    url(r'^$', Home.as_view(), name='home')
)

council/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required, permission_required

from council.views import Home, PaymentOrderList, Dashboard, ChangeTax, TaxList, Receipt, ChangePaymentOrder, \
    EditProfile, ProfileList, set_momo_payment, confirm_payment, PaymentList, BookParking, Maps,\
    notify_outdated_payment_orders, ChangeProfile, ChangeBanner, BannerList, ProjectList, ChangeProject, CategoryList,\
    ChangeCategory, ChangeCheck, CheckList, SubmitBuildingLicenceApplication, SubmitWeddingApplication, \
    BuyWeddingApplication, BuyBuildingLicence, WeddingApplicationList, ChangeWeddingApplication, \
    BuildingLicenceApplicationList, ChangeBuildingLicenceApplication

urlpatterns = patterns(
    '',

    url(r'^kmth/dashboard/$', permission_required('council.ik_view_dashboard')(Dashboard.as_view()), name='dashboard'),

    url(r'^kmth/payments/$', permission_required('council.ik_manage_payment')(PaymentList.as_view()), name='payment_list'),

    url(r'^kmth/categoryList/$', permission_required('council.ik_manage_category')(CategoryList.as_view()), name='category_list'),
    url(r'^kmth/changeCategory/$', permission_required('council.ik_manage_category')(ChangeCategory.as_view()), name='change_category'),
    url(r'^kmth/changeCategory/(?P<object_id>[-\w]+)$', permission_required('council.ik_manage_category')(ChangeCategory.as_view()), name='change_category'),

    url(r'^kmth/taxList/$', permission_required('council.ik_manage_tax')(TaxList.as_view()), name='tax_list'),
    url(r'^kmth/changeTax/$', permission_required('council.ik_manage_tax')(ChangeTax.as_view()), name='change_tax'),
    url(r'^kmth/changeTax/(?P<object_id>[-\w]+)$', permission_required('council.ik_manage_tax')(ChangeTax.as_view()), name='change_tax'),

    url(r'^kmth/changeProfile/$', permission_required('council.ik_view_profile')(ChangeProfile.as_view()), name='change_profile'),
    url(r'^kmth/changeProfile/(?P<object_id>[-\w]+)/$', permission_required('council.ik_view_profile')(ChangeProfile.as_view()), name='change_profile'),
    url(r'^kmth/profileList/$', permission_required('council.ik_view_profile')(ProfileList.as_view()), name='profile_list'),

    url(r'^kmth/weddingApplicationList/$', permission_required('council.ik_manage_wedding')(WeddingApplicationList.as_view()),
        name='wedding_application_list'),
    url(r'^kmth/changeWeddingApplication/$', permission_required('council.ik_manage_wedding')(ChangeWeddingApplication.as_view()),
        name='change_weddingapplication'),
    url(r'^kmth/changeWeddingApplication/(?P<object_id>[-\w]+)$',
        permission_required('council.ik_manage_wedding')(ChangeWeddingApplication.as_view()),
        name='change_weddingapplication'),

    url(r'^kmth/buildingLicenceList/$', permission_required('council.ik_manage_building_licence')(BuildingLicenceApplicationList.as_view()),
        name='building_licence_list'),
    url(r'^kmth/changeBuildingLicence/$',
        permission_required('council.ik_manage_building_licence')(ChangeBuildingLicenceApplication.as_view()),
        name='change_buildinglicenceapplication'),
    url(r'^kmth/changeBuildingLicence/(?P<object_id>[-\w]+)$',
        permission_required('council.ik_manage_building_licence')(ChangeBuildingLicenceApplication.as_view()),
        name='change_buildinglicenceapplication'),

    url(r'^kmth/changeProject/$', permission_required('council.ik_manage_project')(ChangeProject.as_view()), name='change_project'),
    url(r'^kmth/changeProject/(?P<object_id>[-\w]+)/$', permission_required('council.ik_manage_project')(ChangeProject.as_view()), name='change_project'),
    url(r'^kmth/projectList/$', permission_required('council.ik_manage_project')(ProjectList.as_view()), name='project_list'),

    url(r'^kmth/paymentOrderList$', permission_required('council.ik_manage_payment_order')(PaymentOrderList.as_view()), name='paymentorder_list'),
    url(r'^kmth/changePaymentOrder/$', permission_required('council.ik_manage_payment_order')(ChangePaymentOrder.as_view()), name='change_paymentorder'),
    url(r'^kmth/changePaymentOrder/(?P<object_id>[-\w]+)$', permission_required('council.ik_manage_payment_order')(ChangePaymentOrder.as_view()), name='change_paymentorder'),

    url(r'^kmth/bannerList/$', permission_required('council.ik_manage_tax')(BannerList.as_view()), name='banner_list'),
    url(r'^kmth/changeBanner/$', permission_required('council.ik_manage_tax')(ChangeBanner.as_view()), name='change_banner'),
    url(r'^kmth/changeBanner/(?P<object_id>[-\w]+)$', permission_required('council.ik_manage_tax')(ChangeBanner.as_view()), name='change_banner'),

    url(r'^kmth/checkList/$', permission_required('council.ik_manage_tax')(CheckList.as_view()), name='check_list'),
    url(r'^kmth/changeCheck/$', permission_required('council.ik_manage_tax')(ChangeCheck.as_view()), name='change_check'),
    url(r'^kmth/changeCheck/(?P<object_id>[-\w]+)$', permission_required('council.ik_manage_tax')(ChangeCheck.as_view()), name='change_check'),


    # url(r'^home/$', Home.as_view(), name='home'),
    url(r'^profile/edit$', login_required(EditProfile.as_view()), name='edit_profile'),
    url(r'^maps$', login_required(Maps.as_view()), name='maps'),
    url(r'^wedding/apply$', login_required(SubmitWeddingApplication.as_view()), name='submit_wedding_application'),
    url(r'^wedding/application/buy$', login_required(BuyWeddingApplication.as_view()), name='buy_wedding_application'),
    url(r'^buildingLicence/apply$', login_required(SubmitBuildingLicenceApplication.as_view()),
        name='building_licence_application'),
    url(r'^buildingLicence/application/buy$', login_required(BuyBuildingLicence.as_view()),
        name='buy_building_licence'),
    url(r'^receipt/(?P<receipt_id>[-\w]+)/$', login_required(Receipt.as_view()), name='receipt'),
    url(r'^bookParking/$', login_required(BookParking.as_view()), name='book_parking'),

    url(r'^set_momo_payment$', set_momo_payment),
    url(r'^confirm_payment/(?P<object_id>[-\w]+)$', confirm_payment, name='confirm_payment'),
    url(r'^confirm_payment/(?P<object_id>[-\w]+)/(?P<signature>[-\w]+)$', confirm_payment, name='confirm_payment'),

    url(r'^notif$', notify_outdated_payment_orders, name='notify_outdated_payment_orders'),
)

templates/core/app_base_admin.html
{% extends "core/base_admin.html" %}
{% load i18n cache auth_tokens %}

{% block app_admin_nav %}
    <ul class="nav nav-pills nav-stacked">
        {% if perms.pinsview.ik_manage_tax %}
            <li role="presentation" class="banners">
                <a href="{% url 'council:change_banner' %}">{% trans "Banner" %}</a>
            </li>
        {% endif %}
        {% if perms.council.ik_view_dashboard %}
            <li role="presentation" class="dashboard">
                <a href="{% url 'ikwen:dashboard' %}">{% trans "Dashboard" %}</a>
            </li>
        {% endif %}
        {% if perms.council.ik_manage_category %}
            <li role="presentation" class="categories">
                <a href="{% url 'council:category_list' %}">{% trans "Business Types" %}</a>
            </li>
        {% endif %}
        {% if perms.council.ik_view_profile %}
            <li role="presentation" class="profiles">
                <a href="{% url 'council:profile_list' %}">{% trans "Profiles" %}</a>
            </li>
        {% endif %}
{#        {% if perms.pinsview.ik_manage_payment_order %}#}
{#            <li role="presentation" class="paymentorders">#}
{#                <a href="{% url 'council:paymentorder_list' %}">{% trans "Payment Orders" %}</a>#}
{#            </li>#}
{#        {% endif %}#}
        <li role="presentation" class="parking">
            <a href="javascript:;" data-toggle="collapse" data-target="#parking"
               aria-expanded="true" style="padding-right: 0;">Parking
                <i class="fa fa-fw fa-caret-down"></i>
            </a>
            {% if perms.pinsview.ik_manage_pins or perms.pinsview.ik_setup_pinsview %}
                <ul id="parking" class="nav nav-pills nav-stacked collapse" aria-expanded="true" style="padding-left: 15px">
                    {% if perms.council.ik_manage_product %}
                        <li role="presentation" class="products">
                            <a href="{% url 'council:tax_list' %}">{% trans "Taxes" %}</a>
                        </li>
                    {% endif %}
                    {% if perms.council.ik_manage_subscription %}
                        <li role="presentation" class="checks">
                            <a href="{% url 'council:check_list' %}">{% trans "Checks" %}</a>
                        </li>
                    {% endif %}
                    {% if perms.council.ik_manage_subscription %}
                        <li role="presentation" class="subscriptions">
                            <a href="{% url 'billing:subscription_list' %}">{% trans "Subscriptions" %}</a>
                        </li>
                    {% endif %}
                    {% if perms.council.ik_manage_payment %}
                        <li role="presentation" class="payments">
                            <a href="{% url 'billing:payment_list' %}">{% trans "Payments" %}</a>
                        </li>
                    {% endif %}
                </ul>
            {% endif %}
        </li>
        <li role="presentation" class="geolocation">
            <a href="javascript:;" data-toggle="collapse" data-target="#geolocation"
               aria-expanded="true" style="padding-right: 0;">Pinsview
                <i class="fa fa-fw fa-caret-down"></i>
            </a>
            {% if perms.pinsview.ik_manage_pins or perms.pinsview.ik_setup_pinsview %}
                <ul id="geolocation" class="nav nav-pills nav-stacked collapse" aria-expanded="true" style="padding-left: 15px">
                    {% if perms.pinsview.ik_manage_pins %}
                        <li role="presentation" class="pins">
                            <a href="{% url 'pinsview:pin_list' %}">{% trans "Pins" %}</a>
                        </li>
                    {% endif %}
                    {% if perms.pinsview.ik_setup_pinsview %}
                        <li role="presentation" class="pin-categories">
                            <a href="{% url 'pinsview:pincategory_list' %}">{% trans "Pin categories" %}</a>
                        </li>
                        <li role="presentation" class="cities">
                            <a href="{% url 'pinsview:city_list' %}">{% trans "Locations" %}</a>
                        </li>
                    {% endif %}
                    <div class="divider"></div>
                    <li class="logeventtypes">{% url 'pinsview:logeventtype_list' as log_event_type_list_url %}
                        <a href="{{ log_event_type_list_url }}">{% trans "Log Event Types" %}</a>
                    </li>
                    <li class="logevents">{% url 'pinsview:assetlog_list' as asset_log_list_url %}
                        <a href="{{ asset_log_list_url }}">{% trans "Assets Log" %}</a>
                    </li>
                </ul>
            {% endif %}
        </li>
        <li role="presentation" class="applications">
            <a href="javascript:;" data-toggle="collapse" data-target="#applications"
               aria-expanded="true" style="padding-right: 0;">{% trans "Applications" %}
                <i class="fa fa-fw fa-caret-down"></i>
            </a>
            {% if perms.council.ik_manage_wedding or perms.council.ik_setup_manage_wedding or perms.council.ik_setup_manage_building_licence or perms.council.ik_manage_invoice %}
                <ul id="applications" class="nav nav-pills nav-stacked collapse" aria-expanded="true" style="padding-left: 15px">
                    {% if perms.council.ik_manage_wedding %}
                        <li role="presentation" class="wedding-applications">
                            <a href="{% url 'council:wedding_application_list' %}">{% trans "Weddings" %}</a>
                        </li>
                    {% endif %}
                    {% if perms.council.ik_setup_manage_wedding %}
                        <li role="presentation" class="building-licence-applications">
                            <a href="{% url 'council:building_licence_list' %}">{% trans "Building Licences" %}</a>
                        </li>
                    {% endif %}
                    {% if perms.council.ik_setup_manage_building_licence %}
                        <li role="presentation" class="projects">
                            <a href="{% url 'council:project_list' %}">{% trans "Projects" %}</a>
                        </li>
                    {% endif %}
                    {% if perms.council.ik_manage_invoice %}
                        <li role="presentation" class="invoices">
                            <a href="{% url 'billing:invoice_list' %}">{% trans "Invoices" %}</a>
                        </li>
                    {% endif %}
                </ul>
            {% endif %}
        </li>
        {% if perms.echo.ik_manage_messaging %}
            <li role="presentation" class="messaging-campaign">
                <a href="javascript:;" data-toggle="collapse" data-target="#messaging-campaigns"
                   aria-expanded="true" style="padding-right: 0;">
                    {% trans "Messaging Campaigns" %}
                    <i class="fa fa-fw fa-caret-down"></i>
                </a>
                <ul id="messaging-campaigns" class="nav nav-pills nav-stacked collapse" aria-expanded="true"
                    style="padding-left: 15px">
                    <li class="sms-campaigns">{% url 'echo:sms_campaign' as sms_campaign_url %}
                        <a href="{{ sms_campaign_url }}">{% trans "SMS" %}</a>
                    </li>
                    <li class="mail-campaigns">{% url 'echo:mailcampaign_list' as mail_campaign_url %}
                        <a href="{{ mail_campaign_url }}">
                            {% trans "Mail" %}
                            <span class="label label-danger" style="text-transform: capitalize">New</span>
                        </a>
                    </li>
                </ul>
            </li>
        {% endif %}
    </ul>
{% endblock %}