conf/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from ikwen_webnode.webnode.views import FlatPageView

from council.views import Home
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'conf.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    # url(r'^$', Home.as_view(), name='home'),
    url(r'^laakam/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^billing/', include('ikwen.billing.urls', namespace='billing')),
    url(r'^cashout/', include('ikwen.cashout.urls', namespace='cashout')),
    url(r'^theming/', include('ikwen.theming.urls', namespace='theming')),
    url(r'^revival/', include('ikwen.revival.urls', namespace='revival')),
    url(r'^ikwen/', include('ikwen.core.urls', namespace='ikwen')),

    url(r'^page/(?P<url>[-\w]+)/$', FlatPageView.as_view(), name='flatpage'),
    url(r'^blog/', include('ikwen_webnode.blog.urls', namespace='blog')),
    url(r'^web/', include('ikwen_webnode.web.urls', namespace='web')),
    url(r'^items/', include('ikwen_webnode.items.urls', namespace='items')),
    url(r'^echo/', include('echo.urls', namespace='echo')),
    url(r'^rewarding/', include('ikwen.rewarding.urls', namespace='rewarding')),
    url(r'^pinsview/', include('pinsview.urls', namespace='pinsview')),

    url(r'^reporting/', include('ikwen_foulassi.reporting.urls', namespace='reporting')),
    url(r'^school/', include('ikwen_foulassi.school.urls', namespace='school')),
    url(r'^foulassi/', include('ikwen_foulassi.foulassi.urls', namespace='foulassi')),
    url(r'^', include('council.urls', namespace='council')),
    url(r'^$', Home.as_view(), name='home')
)

council/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required, permission_required

from council.views import Home, PaymentOrderList, Dashboard, ChangeTax, TaxList, Receipt, ChangePaymentOrder, \
    EditProfile, ProfileList, set_momo_payment, confirm_payment, PaymentList, BookParking, Maps,\
    notify_outdated_payment_orders, ChangeProfile, ChangeBanner, BannerList, ProjectList, ChangeProject, CategoryList,\
    ChangeCategory, ChangeCheck, CheckList, SubmitBuildingLicenceApplication, SubmitWeddingApplication, \
    BuyWeddingApplication, BuyBuildingLicence, WeddingApplicationList, ChangeWeddingApplication, \
    BuildingLicenceApplicationList, ChangeBuildingLicenceApplication

urlpatterns = patterns(
    '',

    url(r'^kmth/dashboard/$', permission_required('council.ik_view_dashboard')(Dashboard.as_view()), name='dashboard'),

    url(r'^kmth/payments/$', permission_required('council.ik_manage_payment')(PaymentList.as_view()), name='payment_list'),

    url(r'^kmth/categoryList/$', permission_required('council.ik_manage_category')(CategoryList.as_view()), name='category_list'),
    url(r'^kmth/changeCategory/$', permission_required('council.ik_manage_category')(ChangeCategory.as_view()), name='change_category'),
    url(r'^kmth/changeCategory/(?P<object_id>[-\w]+)$', permission_required('council.ik_manage_category')(ChangeCategory.as_view()), name='change_category'),

    url(r'^kmth/taxList/$', permission_required('council.ik_manage_tax')(TaxList.as_view()), name='tax_list'),
    url(r'^kmth/changeTax/$', permission_required('council.ik_manage_tax')(ChangeTax.as_view()), name='change_tax'),
    url(r'^kmth/changeTax/(?P<object_id>[-\w]+)$', permission_required('council.ik_manage_tax')(ChangeTax.as_view()), name='change_tax'),

    url(r'^kmth/changeProfile/$', permission_required('council.ik_view_profile')(ChangeProfile.as_view()), name='change_profile'),
    url(r'^kmth/changeProfile/(?P<object_id>[-\w]+)/$', permission_required('council.ik_view_profile')(ChangeProfile.as_view()), name='change_profile'),
    url(r'^kmth/profileList/$', permission_required('council.ik_view_profile')(ProfileList.as_view()), name='profile_list'),

    url(r'^kmth/weddingApplicationList/$', permission_required('council.ik_manage_wedding')(WeddingApplicationList.as_view()),
        name='wedding_application_list'),
    url(r'^kmth/changeWeddingApplication/$', permission_required('council.ik_manage_wedding')(ChangeWeddingApplication.as_view()),
        name='change_weddingapplication'),
    url(r'^kmth/changeWeddingApplication/(?P<object_id>[-\w]+)$',
        permission_required('council.ik_manage_wedding')(ChangeWeddingApplication.as_view()),
        name='change_weddingapplication'),

    url(r'^kmth/buildingLicenceList/$', permission_required('council.ik_manage_building_licence')(BuildingLicenceApplicationList.as_view()),
        name='building_licence_list'),
    url(r'^kmth/changeBuildingLicence/$',
        permission_required('council.ik_manage_building_licence')(ChangeBuildingLicenceApplication.as_view()),
        name='change_buildinglicenceapplication'),
    url(r'^kmth/changeBuildingLicence/(?P<object_id>[-\w]+)$',
        permission_required('council.ik_manage_building_licence')(ChangeBuildingLicenceApplication.as_view()),
        name='change_buildinglicenceapplication'),

    url(r'^kmth/changeProject/$', permission_required('council.ik_manage_project')(ChangeProject.as_view()), name='change_project'),
    url(r'^kmth/changeProject/(?P<object_id>[-\w]+)/$', permission_required('council.ik_manage_project')(ChangeProject.as_view()), name='change_project'),
    url(r'^kmth/projectList/$', permission_required('council.ik_manage_project')(ProjectList.as_view()), name='project_list'),

    url(r'^kmth/paymentOrderList$', permission_required('council.ik_manage_payment_order')(PaymentOrderList.as_view()), name='paymentorder_list'),
    url(r'^kmth/changePaymentOrder/$', permission_required('council.ik_manage_payment_order')(ChangePaymentOrder.as_view()), name='change_paymentorder'),
    url(r'^kmth/changePaymentOrder/(?P<object_id>[-\w]+)$', permission_required('council.ik_manage_payment_order')(ChangePaymentOrder.as_view()), name='change_paymentorder'),

    url(r'^kmth/bannerList/$', permission_required('council.ik_manage_tax')(BannerList.as_view()), name='banner_list'),
    url(r'^kmth/changeBanner/$', permission_required('council.ik_manage_tax')(ChangeBanner.as_view()), name='change_banner'),
    url(r'^kmth/changeBanner/(?P<object_id>[-\w]+)$', permission_required('council.ik_manage_tax')(ChangeBanner.as_view()), name='change_banner'),

    url(r'^kmth/checkList/$', permission_required('council.ik_manage_tax')(CheckList.as_view()), name='check_list'),
    url(r'^kmth/changeCheck/$', permission_required('council.ik_manage_tax')(ChangeCheck.as_view()), name='change_check'),
    url(r'^kmth/changeCheck/(?P<object_id>[-\w]+)$', permission_required('council.ik_manage_tax')(ChangeCheck.as_view()), name='change_check'),


    # url(r'^home/$', Home.as_view(), name='home'),
    url(r'^profile/edit$', login_required(EditProfile.as_view()), name='edit_profile'),
    url(r'^maps$', login_required(Maps.as_view()), name='maps'),
    url(r'^wedding/apply$', login_required(SubmitWeddingApplication.as_view()), name='submit_wedding_application'),
    url(r'^wedding/application/buy$', login_required(BuyWeddingApplication.as_view()), name='buy_wedding_application'),
    url(r'^buildingLicence/apply$', login_required(SubmitBuildingLicenceApplication.as_view()),
        name='building_licence_application'),
    url(r'^buildingLicence/application/buy$', login_required(BuyBuildingLicence.as_view()),
        name='buy_building_licence'),
    url(r'^receipt/(?P<receipt_id>[-\w]+)/$', login_required(Receipt.as_view()), name='receipt'),
    url(r'^bookParking/$', login_required(BookParking.as_view()), name='book_parking'),

    url(r'^set_momo_payment$', set_momo_payment),
    url(r'^confirm_payment/(?P<object_id>[-\w]+)$', confirm_payment, name='confirm_payment'),
    url(r'^confirm_payment/(?P<object_id>[-\w]+)/(?P<signature>[-\w]+)$', confirm_payment, name='confirm_payment'),

    url(r'^notif$', notify_outdated_payment_orders, name='notify_outdated_payment_orders'),
)

council/forms.py
from django import forms

from ikwen.accesscontrol.models import Member

from council.models import Category, ActivityCategory


class ProfileForm(forms.Form):
    member = forms.ModelChoiceField(queryset=Member.objects.all())
    id_number = forms.CharField(max_length=100, required=True,
                                error_messages={'required': 'Please enter your ID card number'})
    location_lat = forms.FloatField(required=False)
    location_lng = forms.FloatField(required=False)
    formatted_address = forms.CharField(max_length=250, required=False)
    taxpayer = forms.CharField(max_length=100, required=False)
    company_name = forms.CharField(max_length=100, required=False)
    business_type = forms.ModelChoiceField(queryset=Category.objects.all())
    # activity_category = forms.ModelChoiceField(queryset=ActivityCategory)

council/templates/council/buy_building_licence.html
{% extends "website/base.html" %}

{% load i18n humanize static auth_tokens webdesign %}

{% block title %}
    <title>{% blocktrans with project_name=config.project_name %}Congratulations!!! Your building licence application has been submitted &centerdot; {{ project_name }}{% endblocktrans %}</title>
{% endblock %}

{% block page_content %}
    <div id="content" class="building-licence-application">
        <div class="container" style="padding-top: 12vh">
            <h2 class="text-center">{% trans "You successfully submit your builder licence application!" %}</h2>
            <div class="col-md-4" style="margin: auto; float: none">
                <a href="{{ invoice_url }}" class="btn btn-sm btn-block btn-deep-blue">{% trans "Pay now" %}</a>
            </div>
        </div>
    </div>
{% endblock %}

council/templates/council/buy_wedding_application.html
{% extends "website/base.html" %}

{% load i18n humanize static auth_tokens webdesign %}

{% block title %}
    <title>{% blocktrans with project_name=config.project_name %}Congratulations!!! Your wedding application has been created &centerdot; {{ project_name }}{% endblocktrans %}</title>
{% endblock %}

{% block head_style %}
    {{ block.super }}
    <link href="{% static 'ikwen/css/uploader-single.css' %}?v=20.8.17" media="screen" rel="stylesheet" type="text/css" />
{% endblock %}

{% block page_content %}
    <div id="content" class="wedding-application">
        <div class="container" style="padding-top: 12vh">
            <h2 class="text-center">{% trans "You successfully submit your wedding application!" %}</h2>
            <div class="col-md-4" style="margin: auto; float: none">
                <a href="{{ invoice_url }}" class="btn btn-sm btn-block btn-deep-blue">{% trans "Pay now" %}</a>
            </div>
        </div>
    </div>
{% endblock %}

council/templates/council/change_profile.html
{% extends 'core/change_object_base.html' %}
{% load i18n humanize static auth_tokens %}

{% block admin_content %}
    <div id="admin-content" class="change-form">
        <div class="container-fluid">
            {% if errors %}<p class="alert alert-danger">{{ errors }}</p>{% endif %}
            <form class="admin-form" method="post">{% csrf_token %}
                <input type="hidden" name="label_field" value="{{ label_field }}" />
                <input type="hidden" name="slug_field" value="{{ slug_field }}" />
                {% include 'core/snippets/model_admin_form.html' %}
                {% for media_obj in media_field_list %}
                <div class="col-sm-4 col-lg-3" style="padding-left: 0; margin-right: 15px">
                    <div>
                    {% with media=media_obj %}
                        {% include 'core/snippets/media_uploader_single.html' %}
                    {% endwith %}
                    </div>
                </div>
                {% endfor %}
                <div class="form-group col-xs-12 col-sm-4 col-md-3" style="clear: both; padding-top: 15px">
                    <a href="{% url 'council:profile_list' %}" class="btn btn-sm btn-primary btn-block">{% trans "OK" %}</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block js %}
    {{ block.super }}
{#    <script src="{% static 'ikwen/js/jquery.datetimepicker.full.js' %}"></script>#}
    <script type="text/javascript">
        (function() {
            $('form.admin-form').find('input, select').attr('disabled', true);
            $('div#admin-nav .{{ verbose_name_plural|slugify }}').addClass('active');
        })()
    </script>
{% endblock %}

council/templates/council/dashboard.html
{% extends 'core/dashboard_base.html' %}

{% load i18n humanize staticfiles auth_tokens %}

council/templates/council/edit_profile.html
{% extends 'website/base.html' %}
{% load i18n humanize static auth_tokens webdesign %}

{% block title %}
    <title>{% trans 'Edit your profile' %}</title>
{% endblock %}
{% block page_content %}
    <div id="content" class="profile">
        <h2 class="title main-title text-center">{% trans 'Edit your profile' %}</h2>
        {% for msg in messages %}
            <p class="success" style="padding: 9px">{{ msg }}</p>
        {% endfor %}
        {% if errors %}
            <div class="error-report">
                {{ errors }}
            </div>
        {% endif %}

        <div class="container">
            <form class="col-sm-6" style="float: none; margin: auto" method="post">{% csrf_token %}
                <input type="hidden" id="id-member" name="member" value="{{ user.id }}">
                <input type="hidden" id="id-type" name="type">
                <div class="citizen">
                    <h4 class="main-title" style="">{% trans "Citizen info" %}</h4>
                    <div class="form-group-md">
                        <label for="id-id_number">{% trans 'ID Number:' %}</label>
                        <input id="id-id_number" type="text" class="input-md form-control" name="id_number" {% if obj.id_number %}value="{{ obj.id_number }}"{% endif %}>
                        <div class="clearfix"></div>
                    </div>
                    <div class="form-group-md">
                        <label for="id-location">{% trans 'Location:' %}</label>
                        <div class="clearfix"></div>
                        <span id="show-location" style="margin: 10px 0"></span>
                        {% if request.GET.lat %}
                            <p>
                                <strong style="color: #0a4b3e">{{ request.GET.formatted_address }}</strong>
                                <p style="font-size: 14px">
                                    <span>{% trans "Do you wanna change it ?" %}</span>
                                    <a href="{% url 'council:maps' %}" class="set-location" style="margin: 10px 0; line-height: 25px">{% trans 'Update location' %}</a>
                                </p>
                            </p>
                        {% else %}
                            {% if obj.formatted_address %}
                                <p>
                                    <strong style="color: #0a4b3e">{{ obj.formatted_address }}</strong>
                                    <p style="font-size: 14px">
                                        <span>{% trans "Do you wanna change it ?" %}</span>
                                        <a href="{% url 'council:maps' %}" class="set-location" style="margin: 10px 0; line-height: 25px">{% trans 'Update location' %}</a>
                                    </p>
                                </p>
                            {% else %}
                                <a href="{% url 'council:maps' %}" class="set-location btn btn-sm btn-outline-success" style="margin: 10px 0; line-height: 25px">{% trans 'Set location' %}</a>
                            {% endif %}
                        {% endif %}
                        <div class="clearfix"></div>
                    </div>
                    <input type="hidden" id="id-lat" name="location_lat" value="{% if request.GET.lat %}{{ request.GET.lat }}{% else %}{% if obj.location_lat %}{{ obj.location_lat }}{% endif %}{% endif %}">
                    <input type="hidden" id="id-lng" name="location_lng" value="{% if request.GET.lat %}{{ request.GET.lng }}{% else %}{% if obj.location_lng %}{{ obj.location_lng }}{% endif %}{% endif %}">
                    <input type="hidden" id="id-formatted-address" name="formatted_address" value="{% if request.GET.formatted_address %}{{ request.GET.formatted_address }}{% else %}{% if obj.formatted_address %}{{ obj.formatted_address }}{% endif %}{% endif %}">
                    <div class="clearfix"></div>
                </div>
                <div class="divider"></div>
                <div class="merchant">
                    <h4 class="main-title" style="">{% trans "Merchant" %}</h4>
                    <div class="form-group-md">
                        <label for="id-taxpayer">{% trans 'Taxpayer:' %}</label>
                        <input id="id-taxpayer" type="text" class="input-md form-control" name="taxpayer" {% if obj.taxpayer %}value="{{ obj.taxpayer }}{% endif %}">
                        <div class="clearfix"></div>
                    </div>
                    <div class="clearfix"></div>
                </div>
{#                <div class="divider"></div>#}
                <div class="business-man">
                    <h4 class="main-title">{% trans 'Business man' %}</h4>
                    <div class="form-group-md">
                        <label for="id-business_type">{% trans 'Business type:' %}</label>
                        <select id="id-business_type" name="business_type" class="form-control">
                            {% for category in category_list %}
                                <option value="{{ category.id }}" {% if obj.category %}selected {% else %} {% if forloop.counter == 1 %}selected{% endif %}{% endif %}>{{ category.name }}</option>
                            {% endfor %}
                        </select>
                        <div class="clearfix"></div>
                    </div>
                    <div class="form-group-md">
                        <label for="id-company_name">{% trans 'Company name:' %}</label>
                        <input id="id-company_name" type="text" class="input-md form-control" name="company_name" {% if obj.company_name %}value="{{ obj.company_name }}"{% endif %}>
                        <div class="clearfix"></div>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="col-sm-7" style="margin: auto; float: none">
                    <button class="btn btn-sm btn-block btn-deep-blue">{% trans "Save" %}</button>
                </div>

                <div class="clearfix"></div>
            </form>
        </div>
        <div class="clearfix"></div>
    </div>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script>
        (() => {
            $('.prompt-login').click(() => {
               let image = '{% static 'ikwen/img/login-to-proceed.jpg' %}',
                   title = "{% trans "Login required" %}",
                   message = "{% trans "Please, you need to login to proceed so that we know who is paying." %}",
                   url = "{% url 'ikwen:sign_in' %}?next={% url 'council:edit_profile' %}";
               ikwen.showNoticeDialog(image, title, message, url);
           });
            let taxpayer = localStorage.getItem('taxpayer'),
            companyName = localStorage.getItem('company_name'),
            businessType = localStorage.getItem('business_type'),
            idNumber = localStorage.getItem('id_number');
            if (taxpayer !== null && taxpayer !== '' && $('#id-taxpayer').val() === ''){
                $('#id-taxpayer').val(taxpayer);
            }
            if (companyName !== null && companyName !== '' && $('#id-company_name').val() === '') {
                $('#id-company_name').val(companyName);
            }
            if (idNumber !== null && idNumber !== '' && $('#id-id_number').val() === ''){
                $('#id-id_number').val(idNumber);
            }
            if (businessType !== null && businessType !== '' && $('#id-business_type').val() === '') {
                $('#id-business_type').val(businessType);
            }
            $('.set-location').on('click', () => {
                localStorage.setItem("id_number", $('#id-id_number').val());
                localStorage.setItem("taxpayer", $('#id-taxpayer').val());
                localStorage.setItem("business_type", $('#id-business_type').val());
                localStorage.setItem("company_name", $('#id-company_name').val());
                return;
            });
            {#$(location).on('change')#}
        })()
    </script>
{% endblock %}

council/templates/council/show_tax_list.html
{% extends 'website/base.html' %}
{% load i18n humanize static auth_tokens webdesign media_from_provider %}

{% block page_title %}
<title>{{ service.project_name }} - ikwen CloudCouncil</title>
{% endblock %}

{% block page_content %}
    <div id="top-notice-ctnr" style="display: none">
        <span class="floating-notice has-shade" style="float: none; position: static"> Error goes here </span>
    </div>
    <div id="content">
        <div class="banner" style="background-image: url({% get_media_prefix %}{{ banner.image }})">
{#            <form id="edit-search" class="col-xs-12 col-sm-8 col-sm-offset-2 col-lg-6 col-lg-offset-3">#}
{#                <input id="city" type="text" class="form-control" name="city" placeholder="{% trans "Search marketplace" %}">#}
{#            </form>#}
            <div class="clearfix"></div>
        </div>
        <div class="container-fluid">
            <div id="#taxes">
                <h3 class="main-title text-center">{% trans "Pay your taxes..." %}</h3>
                <div id="results" class="results-stage" style="margin-top: 4vh">
                    {% include 'council/snippets/tax_list_results.html' %}
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
        <div id="wedding-application">
            <div class="overlay">
                <div class="container text-center inner">
                    <h3 class="main-title text-has-shade">{% blocktrans %}Submit your wedding application{% endblocktrans %}</h3>
                    <a href="{% url 'council:submit_wedding_application' %}" class="btn btn-sm btn-outline-success action">{% trans 'Apply' %}</a>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="container-fluid">
            <div style="margin: 150px 0">
                <div class="col-sm-6 hidden-xs">
                    <h3 class="main-title">{% trans 'Digitalize your school and work easier together with Scolarfleet' %}</h3>
                    <div class="description">
                        {% blocktrans %}
                            Built with the idea of collaborative and social platform,
                            Scolarfleet lets staffs, teachers and parents connect and work together
                            to manage the school and students through these following features:
                        {% endblocktrans %}
                        <ul>
                            <li>{% trans 'Students follow up' %}</li>
                            <li>{% trans 'Scores input by teachers' %}</li>
                            <li>{% trans 'Online assignments' %}</li>
                            <li>{% trans 'Report cards generation' %}</li>
                            <li>{% trans 'Detailed Dashboard' %}</li>
                            <li>{% trans 'Also enable to connect & Share students discipline and work with parents' %}</li>
                        </ul>
                    </div>
                    <div class="row col-sm-6">
                        <a href="https://www.ikwen.com/foulassi/scolarfleet/deploy_cloud?is_council=true" class=" btn btn-block btn-deep-blue action">{% trans 'Deploy now' %}</a>
                    </div>
                </div>
                <div class="col-sm-6 hidden-xs" style="background-image: url({% static 'council/img/foulassi-student-follow-up-xs.png' %}); background-size: cover; background-position: center; height: 500px; width: 600px; padding: 135px 15px"></div>
                <div class="visible-xs">
                    <img class="img-responsive col-sm-6 " src="{% static 'council/img/foulassi-student-follow-up-xs.png' %}" style="">
                    <div class="col-sm-6">
                        <h3 class="main-title" style="">{% trans 'Digitalize your school and work easier together with Scolarfleet' %}</h3>
                        <div class="description" style="">
                            {% blocktrans %}
                                Built with the idea of collaborative and social platform,
                                Scolarfleet lets staffs, teachers and parents connect and work together
                                to manage the school and students through these following features:
                            {% endblocktrans %}
                            <ul>
                                <li>{% trans 'Students follow up' %}</li>
                                <li>{% trans 'Scores input by teachers' %}</li>
                                <li>{% trans 'Online assignments' %}</li>
                                <li>{% trans 'Report cards generation' %}</li>
                                <li>{% trans 'Detailed Dashboard' %}</li>
                                <li>{% trans 'Also enable to connect & Share students discipline and work with parents' %}</li>
                            </ul>
                        </div>
                        <div class="row col-sm-6" style="">
                            <a href="?is_council=true" target="_blank" class=" btn btn-block btn-deep-blue action" style="float: none; margin: auto;">{% trans 'Deploy now' %}</a>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
        <div id="builder-licence-application">
            <div class="overlay">
                <div class="container text-center inner">
                    <h3 class="main-title text-has-shade">{% blocktrans %}Apply for a builder licence{% endblocktrans %}</h3>
                    <a href="{% url 'council:building_licence_application' %}" class="btn btn-sm btn-outline-success action">{% trans 'Apply' %}</a>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="container-fluid" style="background: #fff">
            <div style="padding: 100px 0;">
                <div class="col-sm-6 hidden-xs" style="background-image: url({% static 'council/img/online-shopping.jpg' %}); background-size: cover; background-position: center; height: 400px; width:600px"></div>
                <img class="img-responsive visible-xs" src="{% static 'council/img/online-shopping.jpg' %}">
                <div class="col-sm-6">
                    <h3 class="main-title">{% trans 'Reach more customers and sell all your stocks with Kakocase' %}</h3>
                    <div class="description">
                        {% blocktrans %}
                            Kakocase builds for you a persistent customer base and offers your products
                            to this community via continuous automated Mail and SMS reminders.
                            You should consider increasing your available stocks....
                        {% endblocktrans %}
                    </div>
                    <div class="row col-sm-6">
                        <a href="https://www.ikwen.com/tsunami/bundles?is_baf_council=true" target="_blank" class=" btn btn-block btn-deep-blue action">{% trans 'Deploy now' %}</a>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="edit-profile">
            <div class="container text-center inner">
                <h3 class="main-title">{% blocktrans with project_name=service.project_name %}Let the {{ project_name }} know who you are{% endblocktrans %}</h3>
                <a href="{% url 'council:edit_profile' %}" class=" btn btn-sm btn-outline-success action">{% trans 'Edit your profile' %}</a>
            </div>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script>
        (() => {
{#            {% if request.GET.failed %}#}
{#                ikwen.showFloatingNotice("{% blocktrans with name=request.GET.name %}Payment failed{% endblocktrans %}", 'failed');#}
{#            {% else %}#}
{#                ikwen.showFloatingNotice("{% blocktrans with name=request.GET.name %}You successfully paid your tax {{ name }}{% endblocktrans %}");#}
{#            {% endif %}#}
        })()
    </script>
{% endblock %}