conf/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from ikwen_webnode.webnode.views import FlatPageView

from council.views import Home
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'conf.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    # url(r'^$', Home.as_view(), name='home'),
    url(r'^laakam/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^billing/', include('ikwen.billing.urls', namespace='billing')),
    url(r'^cashout/', include('ikwen.cashout.urls', namespace='cashout')),
    url(r'^theming/', include('ikwen.theming.urls', namespace='theming')),
    url(r'^revival/', include('ikwen.revival.urls', namespace='revival')),
    url(r'^ikwen/', include('ikwen.core.urls', namespace='ikwen')),

    url(r'^page/(?P<url>[-\w]+)/$', FlatPageView.as_view(), name='flatpage'),
    url(r'^blog/', include('ikwen_webnode.blog.urls', namespace='blog')),
    url(r'^web/', include('ikwen_webnode.web.urls', namespace='web')),
    url(r'^items/', include('ikwen_webnode.items.urls', namespace='items')),
    url(r'^echo/', include('echo.urls', namespace='echo')),
    url(r'^rewarding/', include('ikwen.rewarding.urls', namespace='rewarding')),
    url(r'^pinsview/', include('pinsview.urls', namespace='pinsview')),

    url(r'^reporting/', include('ikwen_foulassi.reporting.urls', namespace='reporting')),
    url(r'^school/', include('ikwen_foulassi.school.urls', namespace='school')),
    url(r'^foulassi/', include('ikwen_foulassi.foulassi.urls', namespace='foulassi')),
    url(r'^', include('council.urls', namespace='council')),
    url(r'^$', Home.as_view(), name='home')
)

council/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required, permission_required

from council.views import Home, PaymentOrderList, Dashboard, ChangeTax, TaxList, Receipt, ChangePaymentOrder, \
    EditProfile, ProfileList, set_momo_payment, confirm_payment, PaymentList, BookParking, Maps,\
    notify_outdated_payment_orders, ChangeProfile, ChangeBanner, BannerList, ProjectList, ChangeProject, CategoryList,\
    ChangeCategory, ChangeCheck, CheckList, SubmitBuildingLicenceApplication, SubmitWeddingApplication, \
    BuyWeddingApplication, BuyBuildingLicence, WeddingApplicationList, ChangeWeddingApplication, \
    BuildingLicenceApplicationList, ChangeBuildingLicenceApplication

urlpatterns = patterns(
    '',

    url(r'^kmth/dashboard/$', permission_required('council.ik_view_dashboard')(Dashboard.as_view()), name='dashboard'),

    url(r'^kmth/payments/$', permission_required('council.ik_manage_payment')(PaymentList.as_view()), name='payment_list'),

    url(r'^kmth/categoryList/$', permission_required('council.ik_manage_category')(CategoryList.as_view()), name='category_list'),
    url(r'^kmth/changeCategory/$', permission_required('council.ik_manage_category')(ChangeCategory.as_view()), name='change_category'),
    url(r'^kmth/changeCategory/(?P<object_id>[-\w]+)$', permission_required('council.ik_manage_category')(ChangeCategory.as_view()), name='change_category'),

    url(r'^kmth/taxList/$', permission_required('council.ik_manage_tax')(TaxList.as_view()), name='tax_list'),
    url(r'^kmth/changeTax/$', permission_required('council.ik_manage_tax')(ChangeTax.as_view()), name='change_tax'),
    url(r'^kmth/changeTax/(?P<object_id>[-\w]+)$', permission_required('council.ik_manage_tax')(ChangeTax.as_view()), name='change_tax'),

    url(r'^kmth/changeProfile/$', permission_required('council.ik_view_profile')(ChangeProfile.as_view()), name='change_profile'),
    url(r'^kmth/changeProfile/(?P<object_id>[-\w]+)/$', permission_required('council.ik_view_profile')(ChangeProfile.as_view()), name='change_profile'),
    url(r'^kmth/profileList/$', permission_required('council.ik_view_profile')(ProfileList.as_view()), name='profile_list'),

    url(r'^kmth/weddingApplicationList/$', permission_required('council.ik_manage_wedding')(WeddingApplicationList.as_view()),
        name='wedding_application_list'),
    url(r'^kmth/changeWeddingApplication/$', permission_required('council.ik_manage_wedding')(ChangeWeddingApplication.as_view()),
        name='change_weddingapplication'),
    url(r'^kmth/changeWeddingApplication/(?P<object_id>[-\w]+)$',
        permission_required('council.ik_manage_wedding')(ChangeWeddingApplication.as_view()),
        name='change_weddingapplication'),

    url(r'^kmth/buildingLicenceList/$', permission_required('council.ik_manage_building_licence')(BuildingLicenceApplicationList.as_view()),
        name='building_licence_list'),
    url(r'^kmth/changeBuildingLicence/$',
        permission_required('council.ik_manage_building_licence')(ChangeBuildingLicenceApplication.as_view()),
        name='change_buildinglicenceapplication'),
    url(r'^kmth/changeBuildingLicence/(?P<object_id>[-\w]+)$',
        permission_required('council.ik_manage_building_licence')(ChangeBuildingLicenceApplication.as_view()),
        name='change_buildinglicenceapplication'),

    url(r'^kmth/changeProject/$', permission_required('council.ik_manage_project')(ChangeProject.as_view()), name='change_project'),
    url(r'^kmth/changeProject/(?P<object_id>[-\w]+)/$', permission_required('council.ik_manage_project')(ChangeProject.as_view()), name='change_project'),
    url(r'^kmth/projectList/$', permission_required('council.ik_manage_project')(ProjectList.as_view()), name='project_list'),

    url(r'^kmth/paymentOrderList$', permission_required('council.ik_manage_payment_order')(PaymentOrderList.as_view()), name='paymentorder_list'),
    url(r'^kmth/changePaymentOrder/$', permission_required('council.ik_manage_payment_order')(ChangePaymentOrder.as_view()), name='change_paymentorder'),
    url(r'^kmth/changePaymentOrder/(?P<object_id>[-\w]+)$', permission_required('council.ik_manage_payment_order')(ChangePaymentOrder.as_view()), name='change_paymentorder'),

    url(r'^kmth/bannerList/$', permission_required('council.ik_manage_tax')(BannerList.as_view()), name='banner_list'),
    url(r'^kmth/changeBanner/$', permission_required('council.ik_manage_tax')(ChangeBanner.as_view()), name='change_banner'),
    url(r'^kmth/changeBanner/(?P<object_id>[-\w]+)$', permission_required('council.ik_manage_tax')(ChangeBanner.as_view()), name='change_banner'),

    url(r'^kmth/checkList/$', permission_required('council.ik_manage_tax')(CheckList.as_view()), name='check_list'),
    url(r'^kmth/changeCheck/$', permission_required('council.ik_manage_tax')(ChangeCheck.as_view()), name='change_check'),
    url(r'^kmth/changeCheck/(?P<object_id>[-\w]+)$', permission_required('council.ik_manage_tax')(ChangeCheck.as_view()), name='change_check'),


    # url(r'^home/$', Home.as_view(), name='home'),
    url(r'^profile/edit$', login_required(EditProfile.as_view()), name='edit_profile'),
    url(r'^maps$', login_required(Maps.as_view()), name='maps'),
    url(r'^wedding/apply$', login_required(SubmitWeddingApplication.as_view()), name='submit_wedding_application'),
    url(r'^wedding/application/buy$', login_required(BuyWeddingApplication.as_view()), name='buy_wedding_application'),
    url(r'^buildingLicence/apply$', login_required(SubmitBuildingLicenceApplication.as_view()),
        name='building_licence_application'),
    url(r'^buildingLicence/application/buy$', login_required(BuyBuildingLicence.as_view()),
        name='buy_building_licence'),
    url(r'^receipt/(?P<receipt_id>[-\w]+)/$', login_required(Receipt.as_view()), name='receipt'),
    url(r'^bookParking/$', login_required(BookParking.as_view()), name='book_parking'),

    url(r'^set_momo_payment$', set_momo_payment),
    url(r'^confirm_payment/(?P<object_id>[-\w]+)$', confirm_payment, name='confirm_payment'),
    url(r'^confirm_payment/(?P<object_id>[-\w]+)/(?P<signature>[-\w]+)$', confirm_payment, name='confirm_payment'),

    url(r'^notif$', notify_outdated_payment_orders, name='notify_outdated_payment_orders'),
)

templates/website/snippets/edge_panel.html
{% load i18n humanize staticfiles cache auth_tokens %}
<div class="edge-panel-left-container visible-xs">
    <div id="side-nav" class="edge-panel-left subtle-shade" style="margin-left: -300px">
        <div class="wrapper">
            <div class="stage">
                <div class="top-edge-panel" style>
                    <div class="panel-top">
                    <img src="{% static 'council/img/council-logo.png' %}" class="img-responsive text-center" style="margin:auto; width: 60%">
                </div>
                <div class="divider"></div>
                    <ul class="nav nav-pills nav-stacked">
                        <li><a href="#taxes"><i class="fas fa-money-bill"></i><span style="margin-left: 3px">{% trans 'Pay your taxes' %}</span></a></li>
                        <li><a href="https://www.ikwen.com/foulassi/scolarfleet/deploy?is_baf_council=true"><i class="fas fa-school"></i><span style="margin-left: 3px">{% trans 'Digitalize your school' %}</span></a></li>
                        <li><a href="https://www.ikwen.com/tsunami/bundles?is_baf_council=true" target="_blank"><i class="fas fa-shopping-cart"></i><span style="margin-left: 3px">{% trans 'Create your online shop' %}</span></a></li>
                        <li><a href="{% url 'council:change_paymentorder' %}" target="_blank"><i class="fas fa-receipt"></i><span style="margin-left: 3px">{% trans 'Follow a payment order' %}</span></a></li>
                        {% if request.user.is_staff %}<li><a href="{% url 'pinsview:network' %}"><i class="fas fa-map-marker-alt"></i><span>{% trans 'Pinsview' %}</span></a></li>{% endif %}
                        {% if request.user.is_staff %}<li><a href="{% url 'council:book_parking' %}"><i class="fas fa-car"></i><span>{% trans 'Book parking' %}</span></a></li>{% endif %}

                    </ul>
                    <div class="clearfix"></div>

                    <div class="social-icon">
                        <a style="padding-right: 10px; text-decoration: none; transition: 0.2s;" href="https://www.youtube.com/watch?v=BZb0XFs73yc" target="_blank" class="ico-youtube" title="YouTube"><i class="fab fa-youtube-square"></i></a>
                        <a style="padding-right: 10px; text-decoration: none; transition: 0.2s;" href="{{ config.instagram_link }}" target="_blank" class="ico-instagram" title="Instagram"><i class="fab fa-instagram"></i></a>
                        <a style="padding-right: 10px; text-decoration: none; transition: 0.2s;" href="{{ config.twitter_link }}" target="_blank" class="ico-twitter" title="Twitter"><i class="fab fa-twitter-square"></i></a>
                        <a style="padding-right: 10px; text-decoration: none; transition: 0.2s;" href="{{ config.facebook_link }}" target="_blank" class="ico-facebook" title="Facebook"><i class="fab fa-facebook-square"></i></a>
                        <a style="padding-right: 10px; text-decoration: none; transition: 0.2s;" class="ico-whatsapp visible-xs" href="https://wa.me/{{ config.contact_phone }}"><i class="fab fa-whatsapp"></i></a>
                        {% include 'core/snippets/language_switcher.html' %}
                    </div>
                </div>
            </div>

            <div id="footer" class="text-muted">
                &copy; {{ year }} <a class="company-name" href="{{ service.url }}"><strong>{{ config.company_name }}</strong></a>.
                {% trans "All rights reserved." %}
                {% if config.legal_mentions_url %}
                - <a href="{{ config.legal_mentions_url }}" style="color: #666; text-decoration: none">{% trans "Legal mentions" %}</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>